export { default as clearRoot } from './clearRoot';
export { default as cloneTree } from './cloneTree';
export { default as empty } from './empty';
export { default as getBody } from './getBody';
export { default as isDocument } from './isDocument';
export { default as isEmpty } from './isEmpty';
export { default as isFragment } from './isFragment';
export { default as isNode } from './isNode';
export { default as nodeType } from './nodeType';
export { default as nodeTypeMap } from './nodeTypeMap';
export { default as off } from './off';
export { default as on } from './on';
export { default as ownerDocument } from './ownerDocument';
export { default as purify } from './purify';
export { default as removeMatching } from './removeMatching';
export { default as removeScripts } from './removeScripts';
export { default as rootChildren } from './rootChildren';
export { default as Visibility } from './Visibility';
export * from './tags';

export const __repr__ = '[MochiKit.DOM]';
