export { default as clampColorComponent } from './clampColorComponent.js';
export { default as Color } from './Color.js';
export * from './colors'; 
export { default as fromColorString } from './fromColorString.js';
export { default as fromHexString } from './fromHexString.js';
export { default as fromHSL } from './fromHSL.js';
export { default as fromHSLString } from './fromHSLString.js';
export { default as fromHSV } from './fromHSV.js';
export { default as fromName } from './fromName.js';
export { default as fromRGB } from './fromRGB.js';
export { default as fromRGBString } from './fromRGBString.js';
export { default as fromString } from './fromString.js';
export { default as HSLColor } from './HSLColor.js';
export { default as hslToRGB } from './hslToRGB.js';
export { default as hslValue } from './hslValue.js';
export { default as HSVColor } from './HSVColor.js';
export { default as hsvToRGB } from './hsvToRGB.js';
export { default as isColor } from './isColor.js';
export * from './namedColors.js';
export { default as rgbToHSL } from './rgbToHSL.js';
export { default as rgbToHSV } from './rgbToHSV.js';
export { default as toColorPart } from './toColorPart.js';

export const __repr__ = '[MochiKit.Color]';